---
- hosts: hypervisor
#  - role:
#      name: undercloud_setup
  roles:
    - { role: rhn_reg, tags: [ 'register' ] }
    - { role: update_packages, tags: [ 'update_packages' ] }
    - { role: install_packages, tags: [ 'install_packages' ] }
    - { role: user_accounts, tags: [ 'user_accounts' ] }
    - { role: libvirt_config, tags: [ 'libvirt_config' ] }
    - { role: libvirt_net, tags: [ 'libvirt_net' ] }
    - { role: undercloud_setup, tags: [ 'undercloud_setup' ] }
