---
- hosts: hypervisor
  become: true
  tasks:
  - include_role:
      name: rhn_reg
  - include_role:
      name: update_packages
  - include_role:
      name: install_packages
  - include_role:
      name: user_accounts
