- name: define overcloud network
  virt_net:
    command: define 
    name: overcloud
    xml: '{{ lookup("template", "overcloud.xml") }}'
  become: yes
- name: start the network
  virt_net:
    name: overcloud
    autostart: yes
    state: active
  become: yes
- name: define external network
  virt_net:
    command: define 
    name: external
    xml: '{{ lookup("template", "external.xml") }}'
  become: yes
- name: start the external network
  virt_net:
    name: external
    autostart: yes
    state: active
  become: yes
