---
- name: update libvirt config
  lineinfile:
    path: /etc/libvirt/libvirtd.conf 
    insertafter: '^#unix_sock_group*'
    line: 'unix_sock_group = "libvirt"'
  become: yes
  notify: restart libvirtd
- name: update libvirt config again
  lineinfile:
    path: /etc/libvirt/libvirtd.conf 
    insertafter: '^#unix_sock_rw_perms*'
    line: 'unix_sock_rw_perms = "0770"'
  become: yes
  notify: restart libvirtd
