---
# check if deploy succeed
- name: check services
  shell: openstack service list
  environment: "{{ openstack_undercloud_env }}"
  register: services_out
  ignore_errors: true
#
# deploy undercloud
- name: deploy undercloud
  command: openstack undercloud install
  when: services_out.rc != 0
