---
- name: register rhn
  redhat_subscription:
    state: present
    username: "{{ username }}"
    password: "{{ password }}" 
    pool_ids: "{{ pool | replace('\n', '') }}"
    force_register: yes
  become: yes
