---
- name: create directory for undercloud images
  file: 
    path: /home/undercloud
    state: directory
    owner: qemu
    group: qemu
  become: yes
- name: copy iso
  copy:
    src: "{{ src_filename }}"
    dest: /home/undercloud
    owner: qemu
    group: qemu
  become: yes 
- name: undercloud kickstart file
  template:
    src: undercloud.ks
    dest: /home/undercloud/undercloud.ks
    owner: qemu
    group: qemu
    mode: 0644
  become: yes 
